title = "Parameters to create Plant life strategies"
author = "Jo√£o Paulo Darela Filho"

dirichlet_alpha = 1.0

[parameters]
grass_pls_fraction = 0.07
minimum_allocation = 0.10 # Minimum allocation to any pool
base_npp = 0.5 # Base NPP in kg C m-2 yr-1

[residence_time]
woody = {leaf_min = 1, leaf_max = 15.0, wood_min = 1, wood_max = 120.0, root_min = 0.083333, root_max = 15.0}
grass = {leaf_min = 0.083333, leaf_max = 1.0, wood_min = 0.0, wood_max = 0.0, root_min = 0.083333, root_max = 2.0}

[nutrient_carbon_ratios]
leaf_n2c = {min = 0.002, max = 0.05}
leaf_p2c = {min = 0.0002, max = 0.005}

wood_n2c = {min = 0.0008, max = 0.01}
wood_p2c = {min = 1e-5, max =  0.000668}

root_n2c = {min = 0.0021186440677966106, max = 0.09283766326970001}
root_p2c = {min = 6.762295081967214e-6,  max = 0.06929919782697837}
